# Generated by Django 5.2.7 on 2025-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAlunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tb_alunos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=255)),
                ('carga', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_disciplinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbEnderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('regiao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_enderecos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tb_notas',
                'managed': False,
            },
        ),
    ]
