# Generated by Django 5.2.7 on 2025-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbalunos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbdisciplinas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbenderecos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbnotas',
            options={'managed': True},
        ),
    ]
