# Generated by Django 5.2.7 on 2025-10-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_aluno', '0002_alter_tbalunos_options_alter_tbdisciplinas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbalunos',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro_aluno.tbenderecos'),
        ),
        migrations.AddField(
            model_name='tbnotas',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro_aluno.tbalunos'),
        ),
        migrations.AddField(
            model_name='tbnotas',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro_aluno.tbdisciplinas'),
        ),
    ]
