# Generated by Django 5.2.7 on 2025-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_aluno', '0003_tbalunos_endereco_tbnotas_aluno_tbnotas_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbalunos',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
