# Generated by Django 5.2.7 on 2025-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_aluno', '0004_tbalunos_nome_mae'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_carro', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.IntegerField(blank=True, max_length=255, null=True)),
                ('modelo', models.IntegerField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_carros',
                'managed': True,
            },
        ),
    ]
